include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TickTintPrefs

TickTintPrefs_FILES = TTRootListController.m
TickTintPrefs_FRAMEWORKS = UIKit
TickTintPrefs_INSTALL_PATH = /Library/PreferenceBundles
TickTintPrefs_CFLAGS = -fobjc-arc
TickTintPrefs_LDFLAGS = -Wl,-undefined,dynamic_lookup

include $(THEOS_MAKE_PATH)/bundle.mk
